name: betabeta
description: A new Flutter project.

publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.4.69+0.4.69

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.0
  image_picker: ^0.8.5+3
  speech_bubble: ^0.0.9
  http: ^0.13.4
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.11
  flutter_spinkit: ^5.1.0
  flutter_facebook_auth: ^4.4.1
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  page_indicator: ^0.4.1
  provider: ^6.0.1
  carousel_slider: ^4.0.0
  # flutter_switch: ^0.3.0
  intl: ^0.17.0
  rive: ^0.9.1
  fuzzy: ^0.4.0-nullsafety.0
  trotter: ^2.0.0-dev.1
  tuple: ^2.0.0
  reorderables: ^0.5.0
  font_awesome_flutter: ^10.1.0
  photo_view: ^0.13.0
  hive: ^2.0.5
  tutorial_coach_mark: ^1.2.4
  hive_flutter: ^1.1.0
  tcard:
    git:
      url: https://github.com/yoniker/tcard.git
  flutter_chat_ui:
    git:
      url: https://github.com/nit900/flutter_chat_ui_voila.git
  path_provider: ^2.0.8
  image: ^3.1.0
  auth_buttons: ^2.0.3
  firebase_core: ^1.10.6
  get: ^4.6.5
  animations: ^2.0.2
  firebase_messaging: ^11.2.4
  flutter_local_notifications: ^9.1.5
  connectivity_plus: ^2.1.0
  firebase_auth: ^3.3.6
  share_plus: ^4.0.10
  video_player: ^2.2.18
  country_code_picker: ^2.0.2
  animated_text_kit: ^4.2.1
  percent_indicator: ^4.2.2
  geolocator: ^8.2.0
  csc_picker: ^0.2.6
  extended_image: ^6.2.1
  pinput: ^2.2.10
  google_fonts: ^2.3.1
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  app_settings: 4.1.5
  modal_bottom_sheet: ^2.0.1
  simple_timer: ^2.0.0

  # publish_to: 'none'
dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
  image_picker_android: 0.8.4+13

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
  #as transparency is not allowed on app store,optional is:
  #remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/images/
    - assets/mock_images/
    - assets/
    - assets/celebs_hive.hive
    - assets/celebs.json
    - assets/onboarding/images/
    - assets/onboarding/videos/
    - assets/rive/
  fonts:
    - family: RougeScript
      fonts:
        - asset: assets/fonts/RougeScript-Regular.ttf

    # The major font used in the App.
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          style: italic
          weight: 900


    # Another option for a font used in the App.
    - family: Yantramanav
      fonts:
        - asset: assets/fonts/Yantramanav/Yantramanav-Thin.ttf
          weight: 100
        - asset: assets/fonts/Yantramanav/Yantramanav-Light.ttf
          weight: 300
        - asset: assets/fonts/Yantramanav/Yantramanav-Regular.ttf
          weight: 400
        - asset: assets/fonts/Yantramanav/Yantramanav-Medium.ttf
          weight: 500
        - asset: assets/fonts/Yantramanav/Yantramanav-Bold.ttf
          weight: 700
        - asset: assets/fonts/Yantramanav/Yantramanav-Black.ttf
          weight: 900

    # A minor font used only for some specific widgets such as the TitleTile of the App.
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
          weight: 500


    - family: AlfaSlabOne
      fonts:
        - asset: assets/fonts/AlfaSlabOne-Regular.ttf

    - family: Playfair_Display
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Black.ttf
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Italic.ttf
          weight: 600





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages