// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_aehoxrbw5dprFdakmHSk7wV_vbNFhmw',
    appId: '1:161944761277:web:4beb0ae3372e1828e158d4',
    messagingSenderId: '161944761277',
    projectId: 'swiper-db2c5',
    authDomain: 'swiper-db2c5.firebaseapp.com',
    storageBucket: 'swiper-db2c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe75-Z2vILX32MhcLwzNY0X18B7oy5H0g',
    appId: '1:161944761277:android:1f84b5cdeaab9b38e158d4',
    messagingSenderId: '161944761277',
    projectId: 'swiper-db2c5',
    storageBucket: 'swiper-db2c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx7k_PAPpuU93Mzge0dADUUPxx0c2-CoM',
    appId: '1:161944761277:ios:3d50d5a6a143a55ae158d4',
    messagingSenderId: '161944761277',
    projectId: 'swiper-db2c5',
    storageBucket: 'swiper-db2c5.appspot.com',
    iosClientId: '161944761277-s6g1g4721gv1v0de7jlrhpnaso5llsbb.apps.googleusercontent.com',
    iosBundleId: 'com.how-look.betabeta',
  );
}
